---
apiVersion: v1
kind: Namespace
metadata:
  name: deployment-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: deployment-demo
  namespace: deployment-demo
spec:
  replicas: 3
  strategy:
    #type: RollingUpdate
    #type: Recreate
    #rollingUpdate:
      #maxSurge: 25%
      #maxUnavailable: 25%
  selector:
    matchLabels:
      app: deployment-demo
  template:
    metadata:
      labels:
        app: deployment-demo
    spec:
      containers:
      - name: deployment-demo
        image: neotkm/pod-healthcheck:v0.03
        #imagePullPolicy: Always
        #imagePullPolicy: Never
        #imagePullPolicy: IfNotPresent

      #restartPolicy: Always

      #imagePullSecrets:
      #  - name: myregistrykey
